<a href="https://colab.research.google.com/github/kausikaaa/Kausika-Codeboosters_Internship_2026/blob/main/Phase_01_Data_Engineering/Day_01_Data_Engineering_GitHub.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
print("Libraries imported successfully")

Libraries imported successfully

In [ ]:
df=pd.read_csv('student_performance.csv')
print('Dataset loaded successfully')

Dataset loaded successfully

In [ ]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [ ]:
print("Shape of dataset:" , df.shape)
print("Number of students:",df.shape[0])
print("Number of columns:",df.shape[1])

Shape of dataset: (30, 13)
Number of students: 30
Number of columns: 13

In [ ]:
print('Columns in the dataset:')
print(df.columns.tolist())

Columns in the dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
print("Data Types:")
print(df.dtypes)

Data Types:
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [ ]:
print("Total missing values:")
print(df.isnull().sum().sum())

Total missing values:
0

In [ ]:
print("Student Names:")
print(df['name'])

Student Names:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [ ]:
print("Departments in this dataset:")
print(df['department'].unique())

print("\nHow many students per department")
print(df['department'].value_counts())

Departments in this dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

How many students per department
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
cs_students=df[df['department']=='Computer Science']

print(f"Number of Computer Science Students: {len(cs_students)}")

Number of Computer Science Students: 13

In [ ]:
high_attendance =df[df['attendance_percentage']>90]
print(f"Number of students with high attendance:{len(high_attendance)}")
print(high_attendance[['name','department','attendance_percentage']])

Number of students with high attendance:10
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [ ]:
df['total_score']=df['math_score']+df['science_score']+df['programming_score']+df['english_score']

top_student=df.loc[df['total_score'].idxmax()]

print("Top student : ")
print(f"Name : {top_student['name']}")
print(f"Department : {top_student['department']}")
print(f"Total Score : {top_student['total_score']}")
print(f"Attendance : {top_student['attendance_percentage']}")

Top student :
Name : Ananya Das
Department : Computer Science
Total Score : 371
Attendance : 98

In [ ]:
#calculate average score per department
dept_avg =df.groupby('department')['total_score'].mean().round(2)

print("Average total score byy department:")
print(dept_avg)

Average total score byy department:
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [ ]:
df_sorted=df.sort_values(by='total_score',ascending=False)
print("top 10 student:")
print(df_sorted[['name','department','total_score','attendance_percentage']].head(10))

top 10 student:
              name        department  total_score  attendance_percentage
9       Ananya Das  Computer Science          371                     98
21     Tanvi Mehta  Computer Science          367                     97
29  Akanksha Yadav  Computer Science          365                     95
4       Arjun Nair  Computer Science          356                     90
7      Divya Singh  Computer Science          356                     96
17  Swati Kulkarni  Computer Science          354                     94
24       Amit Bose  Computer Science          336                     91
12      Suresh Rao  Computer Science          334                     88
19    Nisha Kapoor  Computer Science          327                     89
0     Aarav Sharma  Computer Science          326                     92

MINI PROJECT    
objective    
create a student performance Explorer using      python and pandas      
to analyze student data and generate the     detailed report     
Dataset columns:     
name      
gender      
department      
math_score      
programming_score     
attendance_percentage      
total_score      
Tasks to Perform:
1. Display Project Title
Print a formatted title with separator lines.
2. Dataset Overview
Display:
- Total number of students
- Total number of columns
- Number of unique departments
3. Department-wise Analysis    
Display the count of students in each department.
4. Score Analysis
Find and display:
- Highest math score
- Lowest math score
- Average math score
- Averuge programming score
- Average attendance percentage
5. Gender-wise Analysis     
Calculate and display average total score grouped by gender.
6. Top Performers      
Display the top 5 students based on total_score.
Show:
- Student Name
- Department
- Total Score
7. Attendance Analysis      
Find students whose attendance is below 75%.
Display:
- Name
- Department
- Attendance Percentage
If all students have attendance above 75%, print a suitable message.
Concepts to Use:
-pandas, DataFrame, groupby(), value_counts(), mean(), max(), min(), sort_values(), iterrows(), Conditional statements, f-strings